### ISSUE TITLE
Problem running it on OSX Yosemite.

### ISSUE THREAD

**Issue by viclib** [ryantrinkle/ghcjs-setup#3]
vh:ghcjs-setup apple1$ ./ghcjs-setup.sh 
If you have any trouble with this script, please submit an issue at https://github.com/ryantrinkle/ghcjs-setup/issues
/Users/apple1/.nix-profile/bin/nix-shell
Entering the ghcjs/nodejs sandbox; this may take several hours the first time you run it
/Users/apple1/.nix-profile/bin/nix-shell: line 3: use: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 4: use: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 5: use: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 6: use: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 7: use: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 9: binmode: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 11: my: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 12: my: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 13: my: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 14: my: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 15: my: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 16: my: command not found
/Users/apple1/.nix-profile/bin/nix-shell: line 18: syntax error near unexpected token `('
/Users/apple1/.nix-profile/bin/nix-shell: line 18: `my @instArgs = ();'
It looks like a problem occurred.  Please submit an issue at https://github.com/ryantrinkle/ghcjs-setup/issues

**Comment by viclib** [comment]
After solving it, now I have:




areadlink.c:38:24: error: use of undeclared identifier 'AT_FDCWD'
cc -DHAVE_CONFIG_H -DEXEEXT=\"\" -I. -I..  -I../intl -I../intl -DDEPENDS_ON_LIBICONV=1 -DDEPENDS_ON_LIBINTL=1   -D_FORTIFY_SOURCE=0 -c -o mbchar.o mbchar.c
  return careadlinkat (AT_FDCWD, filename, NULL, 0, NULL, careadlinkatcwd);
                       ^
1 error generated.
building mbiter.o
make[5]: *** [areadlink.o] Error 1
make[5]: *** Waiting for unfinished jobs....
careadlinkat.c:51:13: error: use of undeclared identifier 'AT_FDCWD'
  if (fd != AT_FDCWD)
            ^
1 error generated.
make[5]: *** [careadlinkat.o] Error 1
make[5]: Leaving directory `/private/var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/nix-build-gettext-0.18.2.drv-0/gettext-0.18.2/gettext-runtime/gnulib-lib'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/private/var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/nix-build-gettext-0.18.2.drv-0/gettext-0.18.2/gettext-runtime/gnulib-lib'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/private/var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/nix-build-gettext-0.18.2.drv-0/gettext-0.18.2/gettext-runtime/gnulib-lib'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/private/var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/nix-build-gettext-0.18.2.drv-0/gettext-0.18.2/gettext-runtime'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/private/var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/nix-build-gettext-0.18.2.drv-0/gettext-0.18.2/gettext-runtime'
make: *** [all-recursive] Error 1
builder for ‘/nix/store/fc22jk19v411pdsmampcs3ji0i9vqz6j-gettext-0.18.2.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/wsa5z4nll5is1366yq59zqidhaajqyvs-gcc-4.8.4.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/06m488vapdxa86427ypwzgji5zc9dwqg-git-2.1.4.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/p20406jana896x4phfcknwgzd90xvank-git-2.1.4.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/nlkvbw7zpxr9gairblfw2jzllcl436ly-ncurses-5.9’
cannot build derivation ‘/nix/store/gs4rflzm726py3sibxg2d43cmv7p53r9-haskell-ghcjs-ghc7.8.4-0.1.0-shared.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/wng1yxkm8jgqvgvpl0vqkra0n4y1hkp9-ghcjs-ghc7.8.4-0.1.0-wrapper.drv’: 1 dependencies couldn't be built
killing process 35569
error: build of ‘/nix/store/wng1yxkm8jgqvgvpl0vqkra0n4y1hkp9-ghcjs-ghc7.8.4-0.1.0-wrapper.drv’ failed
/Users/apple1/.nix-profile/bin/nix-shell: failed to build all dependencies
It looks like a problem occurred.  Please submit an issue at https://github.com/ryantrinkle/ghcjs-setup/issues

**Comment by viclib** [comment]
Last error is:

[75 of 78] Compiling Distribution.Simple.SrcDist ( boot/cabal/Cabal/Distribution/Simple/SrcDist.hs, boot/cabal/Cabal/dist/setup/Distribution/Simple/SrcDist.js_o )
[76 of 78] Compiling Distribution.Simple.Configure ( boot/cabal/Cabal/Distribution/Simple/Configure.hs, boot/cabal/Cabal/dist/setup/Distribution/Simple/Configure.js_o )
[77 of 78] Compiling Distribution.Simple ( boot/cabal/Cabal/Distribution/Simple.hs, boot/cabal/Cabal/dist/setup/Distribution/Simple.js_o )
[78 of 78] Compiling Main             ( boot/cabal/Cabal/dist/setup/setup.hs, boot/cabal/Cabal/dist/setup/Main.js_o )
Linking ./boot/cabal/Cabal/dist/setup/setup.jsexe (Distribution.Compat.CopyFile,Distribution.Compat.CreatePipe,Distribution.Compat.Environment,Distribution.Compat.Exception,Distribution.Compat.ReadP,Distribution.Compat.TempFile,Distribution.Compiler,Distribution.GetOpt,Distribution.InstalledPackageInfo,Distribution.License,Distribution.ModuleName,Distribution.Package,Distribution.PackageDescription,Distribution.PackageDescription.Check,Distribution.PackageDescription.Configuration,Distribution.PackageDescription.Parse,Distribution.PackageDescription.Utils,Distribution.ParseUtils,Distribution.ReadE,Distribution.Simple,Distribution.Simple.Bench,Distribution.Simple.Build,Distribution.Simple.Build.Macros,Distribution.Simple.Build.PathsModule,Distribution.Simple.BuildPaths,Distribution.Simple.BuildTarget,Distribution.Simple.CCompiler,Distribution.Simple.Command,Distribution.Simple.Compiler,Distribution.Simple.Configure,Distribution.Simple.GHC,Distribution.Simple.GHC.IPI641,Distribution.Simple.GHC.IPI642,Distribution.Simple.GHC.ImplInfo,Distribution.Simple.GHC.Internal,Distribution.Simple.GHCJS,Distribution.Simple.Haddock,Distribution.Simple.HaskellSuite,Distribution.Simple.Hpc,Distribution.Simple.Install,Distribution.Simple.InstallDirs,Distribution.Simple.JHC,Distribution.Simple.LHC,Distribution.Simple.LocalBuildInfo,Distribution.Simple.PackageIndex,Distribution.Simple.PreProcess,Distribution.Simple.PreProcess.Unlit,Distribution.Simple.Program,Distribution.Simple.Program.Ar,Distribution.Simple.Program.Builtin,Distribution.Simple.Program.Db,Distribution.Simple.Program.Find,Distribution.Simple.Program.GHC,Distribution.Simple.Program.HcPkg,Distribution.Simple.Program.Hpc,Distribution.Simple.Program.Ld,Distribution.Simple.Program.Run,Distribution.Simple.Program.Script,Distribution.Simple.Program.Strip,Distribution.Simple.Program.Types,Distribution.Simple.Register,Distribution.Simple.Setup,Distribution.Simple.SrcDist,Distribution.Simple.Test,Distribution.Simple.Test.ExeV10,Distribution.Simple.Test.LibV09,Distribution.Simple.Test.Log,Distribution.Simple.UHC,Distribution.Simple.UserHooks,Distribution.Simple.Utils,Distribution.System,Distribution.TestSuite,Distribution.Text,Distribution.Utils.NubList,Distribution.Verbosity,Distribution.Version,Language.Haskell.Extension,Main)
Failed to install Cabal-1.22.0.0
cabal: Error: some packages failed to install:
Cabal-1.22.0.0 failed during the configure step. The exception was:
ExitFailure (-11)
ghcjs-boot: error running: /usr/bin/cabal --config-file /Users/apple1/.ghcjs/x86_64-darwin-0.1.0-7.8.4/ghcjs/cabalBootConfig install ./boot/cabal/Cabal --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /Users/apple1/.cabal/bin/ghcjs --with-hc-pkg /Users/apple1/.cabal/bin/ghcjs-pkg --prefix /Users/apple1/.ghcjs/x86_64-darwin-0.1.0-7.8.4/ghcjs --enable-documentation --haddock-html --haddock-hoogle --haddock-hyperlink-source --enable-library-profiling --root-cmd /Users/apple1/.ghcjs/x86_64-darwin-0.1.0-7.8.4/ghcjs/run.sh
exit status: 1
stderr: Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
cabal: Error: some packages failed to install:
Cabal-1.22.0.0 failed during the configure step. The exception was:
ExitFailure (-11)

**Comment by ryantrinkle** [comment]
Hi, I believe everything should work on Yosemite now; please let me know if you still run into problems!

**Comment by viclib** [comment]
Thanks for the great work! I can't test right now but I surelly will on the next setup. See you :)
