### ISSUE TITLE
Packages added in shell.nix require rebuilding ghc and ghcjs

### ISSUE THREAD

**Issue by conklech** [ryantrinkle/ghcjs-setup#7]
I'm not sure whether this is a documentation issue or a "bug" per se; I'm not yet familiar enough with Nix. (I am running NixOS in a VM.)

shell.nix has a comment: `# Add Haskell packages to your environment here`. After successfully running `ghcjs-setup` unmodified, I tried adding, e.g. `lens` on the next line. This seems to require rebuilding both ghc and ghcjs from source, which is beyond the capability of my VM:

    [christian@nixos:~/ghcjs-setup]$ nix-shell
    these derivations will be built:
      /nix/store/h8gbz8hfpvc86gsndkpr8166v86wrv5y-ghc-7.10.0.20150123.drv
      /nix/store/y711v3jbxkr21ny9snmmak5ysvk8d1rq-ghcjs-0.1.0.drv
    these paths will be fetched (0.00 MiB download, 39.39 MiB unpacked):
      /nix/store/07azljpiya0h4jcw6nvxb9vbjdnp4vcw-haskell-lens-4.7
      [other dependencies]

(And it starts downloading cached binaries from https://ryantrinkle.com:5443/.)

Is this the expected behavior, i.e. not using the same ghc/ghcjs builds in non-`ghcjs-setup` usage? 

(By the way, what I actually want to do is build [the derivation for ocharles's `virtual-dom`](https://github.com/ocharles/virtual-dom/blob/master/shell.nix) with a command ala `NIX_PATH=nixpkgs=/home/$USER/ghcjs-setup/nixpkgs/ nix-shell`, which gives the same sort of result.)

**Comment by ryantrinkle** [comment]
The derivation you see it building there is confusingly named, but, if my understanding is correct, should only be building a ghc/ghcjs *environment*, not ghc or ghcjs itself.  If you notice it rebuilding the actual source files for ghc or ghcjs (which would take about an hour for each one), please reopen this ticket, and I'll take a deeper look into it.

**Comment by conklech** [comment]
You're correct. The build failed for an unrelated reason, and I didn't examine the log closely enough. Thank you!
